cs/README.adoc, cs/SUMMARY.adoc, cs/draw.adoc, cs/vid.adoc, cs/view.adoc
Hello, here am I with my actualization.
Tovim
=> cs-docs: after 0.6.2 changes reflected

en/draw.adoc
:baby_chick: hummingbird's share.
=> FIX: change CLOSED to LARGE in ARC documentation

cs/SUMMARY.adoc, cs/block.adoc, cs/char.adoc, cs/datatype-template.adoc, cs/date.adoc, cs/draw.adoc, cs/float.adoc, cs/glossary.adoc, cs/gui.adoc, cs/integer.adoc, cs/issue.adoc, cs/libred.adoc, cs/logic.adoc, cs/map.adoc, cs/none.adoc, cs/pair.adoc, cs/preprocessor.adoc, cs/reactivity.adoc, cs/style-guide.adoc, cs/tuple.adoc, cs/unset.adoc, cs/vid.adoc, cs/view.adoc
=> Completed and translated everything till 27.5.2018. Hosana!

cs/SUMMARY.adoc
=> Slight formatting change to cseky summary.adoc

en/SUMMARY.adoc, en/datatypes.adoc
Hi, I am sending this new pull request after some pune cleaning. Maybe, it could help.
Tovm
=> @greggirwin, @gltewalt

en/datatypes/get-path.adoc, en/datatypes/lit-path.adoc, en/datatypes/path.adoc, en/datatypes/set-path.adoc
Included Sassenrath quote in Literal Syntax sections.
=> Parse rules for path, get-path, lit-path, set-path

en/datatypes/block.adoc
inspired by: https://gitter.im/red/help?at=5b9813e5728ddf02829371bc
=> accessing block! values

en/datatypes/error.adoc, en/datatypes/time.adoc
Also fixed the Abstract section in error.adoc
The section repeated for a few lines - two Abstract sections.
=> Edits to error.adoc and time.adoc

cs/datatype-template.adoc
=> docs-cs: puny bunny

cs/view.adoc
Sorry for MCh HNY, I have omitted to enclose corrected translation of View
=> docs-cs: better translation of View

cs/datatypes.adoc, cs/datatypes/binary.adoc
=> docs-cs: binary.adoc added, datatypes.adoc modified

cs/datatypes/error.adoc, cs/draw.adoc, cs/view.adoc
error.adoc, draw.adoc and view.adoc
=> docs-cs: dutifully updated the czech translation:

en/draw.adoc
to "rotation angle of the underlying …ellipse in degrees (integer! float!)." -  per issue #69
=> Changed text in Section 3.3.Arc 

en/datatypes/float.adoc
=> Added Runtime Creation section. Expanded Conversion section. 

en/datatypes/tag.adoc
Added mention that < is allowed inside of tag!, and added Note about make.
=> Edited Literal Syntax section of tag.adoc

en/SUMMARY.adoc, en/rtd.adoc
Included rtd.adoc and added link to it in Summary.
=> FEAT: Add Rich-Text Dialect doc

en/SUMMARY.adoc, en/datatypes/paren.adoc
Added Note to 'Testing values' section. Changed code fencing.
=> Edits to paren.adoc

en/preprocessor.adoc
add info about not preserving preprocessor context between included files
discussion: https://gitter.im/red/help?at=5cab27220aad6350194a85cb
=> preprocessor / include: not preserving context

en/datatypes.adoc
=> Added link for string! to datatypes.adoc

cs/datatypes.adoc, cs/datatypes/action.adoc, cs/datatypes/map.adoc, cs/typesets.adoc
A note for @gltewalt : 
Hi, I have found some errors in map.adoc. Will describe them in your private room on Gitter. 
Tovim
=> docs-cs: datatypes.adoc plus DT/(map.adoc, typesets.adoc) translated

cs/datatypes/map.adoc
Typos recently discussed corrected in the czech translation too. Sorry, it could wait till the next translating.
=> docs-cs: DT/map.adoc - changes translated

README.adoc
Created this PR according to this [chat](https://gitter.im/red/docs?at=5cb49341759abc043cc6bbaf)
=> Created README file

cs/datatypes/image.adoc, cs/datatypes/map.adoc, cs/datatypes/pair.adoc
=> docs-cs: recent changes (image.adoc, pair.adoc) translated

cs/datatypes.adoc, cs/datatypes/image.adoc, cs/datatypes/map.adoc, cs/datatypes/native.adoc, cs/datatypes/op.adoc, cs/datatypes/set-word.adoc, cs/datatypes/time.adoc, cs/datatypes/url.adoc, cs/datatypes/word.adoc, cs/draw.adoc, cs/rich-text.adoc, cs/vid.adoc
Hi, I have discovered an untranslated piece of the documentation and going  through the whole text have discovered other needed amendments.
=> docs-cs: last amendments

en/view.adoc
https://github.com/red/red/pull/4225 follow-up, including minor formatting corrections.
=> FEAT: calendar entry in View documentation

en/view.adoc
=> FIX: missing info on default check box state

cs/reactivity.adoc, cs/vid.adoc, cs/view.adoc
=> docs-cs: cs/{reactivity, vid, view}.adoc translated

en/datatypes.adoc, en/datatypes/money.adoc, en/typesets.adoc
Covers `money!` datatype and all related functionality.
=> FEAT: MONEY! datatype documentation.

en/datatypes/money.adoc
Reflects the latest changes in `fast-lexer` branch.
=> FEAT: update MONEY! datatype documentation.

en/datatypes.adoc, en/datatypes/ref.adoc, en/redbin.adoc, en/typesets.adoc
Includes description of the datatype and entry in the Redbin specification.
=> FEAT: REF! datatype documentation.

en/datatypes/money.adoc
https://github.com/red/red/pull/4455 follow-up.
=> FEAT: update section on MONEY! comparison.

en/parse.adoc
A brief mention of the new parsing mode.
=> FEAT: mention matching by datatype in BINARY!.

en/parse.adoc
Per recent [discussion](https://gitter.im/red/help?at=5f0c99923e4a827d19c35da8) in `/help` room.
=> FEAT: mention KEEP COPY Parse idiom.

en/parse.adoc
A late follow-up to https://github.com/red/docs/pull/230.
=> FEAT: minor corrections on the new parsing mode.

README.adoc
=> FIX: a typo

en/parse.adoc
Reflects the changes made after a recent sweep over opened pull requests.
=> FIX: remove resolved Parse issues.

en/natives.adoc
natives listing, if you want it.
=> Created initial natives.adoc
